site:
  title: Реєстр міського електротранспорту
  start_page: docs::index.adoc
content:
  sources:
  - url: https://github.com/ivancheban/demo-component-a.git
    branches: HEAD
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./supplemental-ui
