[build]
base = "/"
publish = "public"

[build.environment]
NODE_VERSION = "18.14.2"
ANTORA_CACHE_DIR = "node_modules/.cache/antora"

[context.production]
command = """\
node_modules/.bin/antora --fetch --generator=@antora/xref-validator ../antora-playbook.yml && \
node_modules/.bin/antora --html-url-extension-style=indexify --redirect-facility=netlify ../antora-playbook.yml && \
curl -o /dev/null -s -X POST -F "token=$INDEX_WEBHOOK_TOKEN" -F "ref=$BRANCH" -F "variables[TRIGGER_ACTION]=index" $INDEX_WEBHOOK_URL\
"""
